# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

FROM 669063966089.dkr.ecr.us-west-2.amazonaws.com/pr-pytorch-training:1.10.2-gpu-py38-cu113-ubuntu20.04-sagemaker-pr-1683-2022-02-14-22-13-55

RUN pip install tensorboard

